app-name: roster
initials: cw
language: gradle

github-app-repo-uri: "git@github.com:ClayWoods/roster.git" # ssh url of your app fork in double quotes. ex: "git@github.com:spgreenberg/roster.git"

github-pipelines-repo-uri: "git@github.com:ClayWoods/training-pipelines.git" # ssh url of your training-pipelines fork in double quotes.  ex: "git@github.com:spgreenberg/training-pipelines.git"

cf-dev-api: http://api.run.pivotal.io # set to cf api endpoint
cf-dev-org: rscale-training-1 # set to your org
cf-dev-space: clay # set to your space
cf-dev-hostname: roster-cwoods # set to '<app-name>-<first_initial><lastname>'. ex: roster-sgreenberg
cf-dev-domain: cfapps.io # set to the apps domain for your CF
cf-dev-manifest: /Users/clay.woods/workspace/STSWorkspace/cfDevClass/roster/rosterManifest.yaml # set to the dev manifest path in your app repository. ex: dev-manifest.yml
